[build-system]
requires = ["hatchling>=1.27"]
build-backend = "hatchling.build"

[project]
name = "zarr-particle-tools"
requires-python = ">=3.10"
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: Implementation :: CPython",
]
dynamic = ["version"]
dependencies = [
    "click",
    "copick",
    "cryoet_alignment>=0.1.1",
    "cryoet_data_portal",
    "dask",
    "mrcfile",
    "numpy",
    "pandas",
    "rich",
    "s3fs",
    "scipy",
    "starfile",
    "zarr",
]
authors = [{ name = "Daniel Ji" }, { name = "Utz Heinrich Ermel" }]
description = "Subtomogram extraction from local files and the CryoET Data Portal."
readme = "README.md"
license = "MIT"
license-files = ["LICENSE"]
keywords = [
    "cryoet",
    "cryo-et",
    "tomography",
    "subtomogram",
    "particle",
    "zarr",
]

[project.urls]
Homepage = "https://github.com/czimaginginstitute/zarr-particle-tools"
Repository = "https://github.com/czimaginginstitute/zarr-particle-tools"
Issues = "https://github.com/czimaginginstitute/zarr-particle-tools/issues"
Changelog = "https://github.com/czimaginginstitute/zarr-particle-tools/blob/main/CHANGELOG.md"

[project.optional-dependencies]
dev = [
    "black>=25.1.0",
    "ccpem-pipeliner",
    "pre-commit>=4.2.0",
    "ruff>=0.12.0",
    "matplotlib",
    "seaborn",
    "pytest",
    "pytest-xdist",
]
pipeliner = ["ccpem-pipeliner"]

[project.scripts]
zarr-particle-extract = "zarr_particle_tools.subtomo_extract:cli"
zarr-particle-reconstruct = "zarr_particle_tools.subtomo_reconstruct:cli"
zarr-particle-ctfrefine = "zarr_particle_tools.subtomo_ctfrefine:cli"
zarr-particle-polish = "zarr_particle_tools.subtomo_polish:cli"
zarr-particle-tomograms = "zarr_particle_tools.generate_tomograms:cli"
zarr-particle-pipeline = "zarr_particle_tools.orchestrate:cli"
zarr-particle-export = "zarr_particle_tools.export_project:cli"

[project.entry-points."ccpem_pipeliner.jobs"]
"zarrparticletools.pseudosubtomo" = "zarr_particle_tools.pipeliner.subtomo_extract_pipeliner_job:PythonRelionPseudoSubtomoJob"
"zarrparticletools.reconstruct" = "zarr_particle_tools.pipeliner.subtomo_reconstruct_pipeliner_job:PythonRelionSubtomoReconstructJob"
"zarrparticletools.ctfrefine" = "zarr_particle_tools.pipeliner.subtomo_ctfrefine_pipeliner_job:PythonRelionSubtomoCtfRefineJob"
"zarrparticletools.polish" = "zarr_particle_tools.pipeliner.subtomo_polish_pipeliner_job:PythonRelionSubtomoPolishJob"

[tool.hatch.version]
path = "src/zarr_particle_tools/__init__.py"

[tool.black]
line-length = 120
target-version = ["py310"]

[tool.ruff]
line-length = 120
target-version = "py310"

[tool.ruff.lint]
select = ["E", "F", "I", "B", "UP"]
ignore = ["E501"]
