"""
Standalone script with modular functions to generate required files for subtomogram extraction from a CryoET Data Portal run.

Note that in the context of the tomograms.star and "individual tomograms" star files, these are analagous with tiltseries.star files
that might be generated by other tools that similarily provide these star files as input to (RELION) subtomogram extraction.

Generates:
- particles.star file for the specified runs and annotations.
- tomograms.star file for the tiltseries.
- tiltseries/*.star files for each tiltseries in the run.
"""

import json
import logging
import time
from concurrent.futures import ThreadPoolExecutor, as_completed
from pathlib import Path

import click
import cryoet_data_portal as cdp
import mrcfile
import numpy as np
import pandas as pd
import starfile
from scipy.spatial.transform import Rotation
from tqdm import tqdm

import cli.options as cli_options
import generate.cdp_cache as cdp_cache
from core.constants import (
    DEFAULT_AMPLITUDE_CONTRAST,
    INDIVIDUAL_TOMOGRAM_ALN_COLUMNS,
    INDIVIDUAL_TOMOGRAM_COLUMNS,
    INDIVIDUAL_TOMOGRAM_CTF_COLUMNS,
    OPTICS_DF_COLUMNS,
    PARTICLES_DF_COLUMNS,
    THREAD_POOL_WORKER_COUNT,
    TILTSERIES_MRCS_PLACEHOLDER,
    TILTSERIES_URI_RELION_COLUMN,
    TOMO_HAND_DEFAULT_VALUE,
)
from core.data import get_data
from core.helpers import get_filter, get_optics_group_name, get_tomo_name, setup_logging
from core.projection import in_plane_rotation_to_tilt_axis_rotation

logger = logging.getLogger(__name__)


def validate_alignment_tiltseries(
    annotation_file: cdp.AnnotationFile, alignment: cdp.Alignment, tiltseries: cdp.TiltSeries
) -> bool:
    if not cdp_cache.get_per_section_alignments_by_alignment_id(alignment.id):
        logger.error(
            f"[Run {alignment.run_id}, Annotation File {annotation_file.id} Alignment {alignment.id}] Missing alignment information. Skipping file."
        )
        return False

    if not cdp_cache.get_per_section_parameters_by_tiltseries_id(tiltseries.id):
        logger.error(
            f"[Run {alignment.run_id}, Annotation File {annotation_file.id} TiltSeries {tiltseries.id}] Missing tiltseries CTF parameters. Skipping file."
        )
        return False

    return True


def validate_and_get_tomogram(
    annotation_file: cdp.AnnotationFile, alignment: cdp.Alignment
) -> tuple[int, int, int, float] | None:
    tomogram_data = set(
        (tomogram.size_x, tomogram.size_y, tomogram.size_z, tomogram.voxel_spacing)
        for tomograms in cdp_cache.get_tomograms_by_alignment_id_and_voxel_spacing_id(
            (alignment.id, annotation_file.tomogram_voxel_spacing_id)
        ).values()
        for tomogram in tomograms
    )

    if len(tomogram_data) != 1:
        logger.error(
            f"[Run {alignment.run_id}, Annotation File {annotation_file.id}] Expected tomograms to have the same size and voxel size, but found {len(tomogram_data)} unique values."
        )
        return pd.DataFrame()

    return list(tomogram_data)[0]


def get_optics_df_from_file(
    annotation_file: cdp.AnnotationFile, alignment: cdp.Alignment, tiltseries: cdp.TiltSeries
) -> pd.DataFrame:
    if not validate_alignment_tiltseries(annotation_file, alignment, tiltseries) or not validate_and_get_tomogram(
        annotation_file, alignment
    ):
        return pd.DataFrame()

    optics_df = pd.DataFrame(columns=OPTICS_DF_COLUMNS)
    optics_group_name = get_optics_group_name(alignment.run_id, tiltseries.id)
    tomo_name = get_tomo_name(alignment.run_id, tiltseries.id, alignment.id, annotation_file.tomogram_voxel_spacing_id)
    optics_df.loc[0] = {
        "rlnOpticsGroup": 1,
        "rlnOpticsGroupName": optics_group_name,
        "rlnSphericalAberration": tiltseries.spherical_aberration_constant,
        "rlnVoltage": tiltseries.acceleration_voltage,
        "rlnAmplitudeContrast": DEFAULT_AMPLITUDE_CONTRAST,
        "rlnTomoTiltSeriesPixelSize": tiltseries.pixel_spacing,
        "rlnTomoName": tomo_name,  # not usually in optics_df, but included so that tomograms.star generation from the optics_df is possible
    }

    return optics_df


def get_particles_df_from_file(
    annotation_file: cdp.AnnotationFile, alignment: cdp.Alignment, tiltseries: cdp.TiltSeries
) -> pd.DataFrame:
    if not validate_alignment_tiltseries(annotation_file, alignment, tiltseries):
        return pd.DataFrame()

    tomogram_data = validate_and_get_tomogram(annotation_file, alignment)

    if not tomogram_data:
        return pd.DataFrame()

    particles_df = pd.DataFrame(columns=PARTICLES_DF_COLUMNS)
    optics_group_name = get_optics_group_name(alignment.run_id, tiltseries.id)
    tomo_name = get_tomo_name(alignment.run_id, tiltseries.id, alignment.id, annotation_file.tomogram_voxel_spacing_id)

    json_data = get_data(annotation_file.s3_path)
    json_point_data = [json.loads(line) for line in json_data.splitlines() if line.strip()]

    pixel_coordinates = [(d["location"]["x"], d["location"]["y"], d["location"]["z"]) for d in json_point_data]
    centered_coordinates = [
        (
            (p[0] - tomogram_data[0] / 2) * tomogram_data[3],
            (p[1] - tomogram_data[1] / 2) * tomogram_data[3],
            (p[2] - tomogram_data[2] / 2) * tomogram_data[3],
        )
        for p in pixel_coordinates
    ]

    # rot, tilt, psi
    euler_angles = (
        [
            Rotation.from_matrix(np.linalg.inv(d["xyz_rotation_matrix"])).as_euler(
                "ZYZ", degrees=True
            )  # TODO: verify this is correct
            for d in json_point_data
        ]
        if "xyz_rotation_matrix" in json_point_data[0]
        else [(0, 0, 0)] * len(pixel_coordinates)
    )

    particles_list = [
        {
            "rlnTomoName": tomo_name,
            "rlnCoordinateX": p[0],
            "rlnCoordinateY": p[1],
            "rlnCoordinateZ": p[2],
            "rlnAngleRot": e[0],
            "rlnAngleTilt": e[1],
            "rlnAnglePsi": e[2],
            "rlnCenteredCoordinateXAngst": c[0],
            "rlnCenteredCoordinateYAngst": c[1],
            "rlnCenteredCoordinateZAngst": c[2],
            "rlnOpticsGroupName": optics_group_name,
            "rlnOpticsGroup": 1,
            "cdpAnnotationShapeId": annotation_file.annotation_shape_id,
        }
        for p, c, e in zip(pixel_coordinates, centered_coordinates, euler_angles)
    ]
    particles_df = pd.DataFrame(particles_list, columns=particles_df.columns)

    logger.debug(
        f"[Run {alignment.run_id}, Annotation File {annotation_file.id}] Processed {len(particles_df)} particles with optics group '{optics_group_name}'."
    )

    return particles_df


def get_particles_df_optics_df(
    annotation_files: list[cdp.AnnotationFile], no_particles: bool = False
) -> tuple[pd.DataFrame, pd.DataFrame | None]:
    """
    Creates particles and optics dataframes necessary for a particles.star file from CryoET Data Portal annotations.
    Args:
        annotation_files (list[AnnotationFile]): List of annotation files to process.
    Returns:
        tuple: A tuple containing the optics dataframe and particles dataframe (combined from all Point and OrientedPoint annotations).
    """
    logger.info("Pulling annotation files from the CryoET Data Portal ...")
    all_optics_dfs: list[pd.DataFrame] = []
    all_particles_dfs: list[pd.DataFrame] = []

    alignments = cdp_cache.get_alignments([file.alignment_id for file in annotation_files if file.alignment_id])
    # filter out alignments that do not have a valid tiltseries
    removed_alignments = [a.id for a in alignments.values() if not a.tiltseries_id]
    if removed_alignments:
        logger.error(
            f"Removed {len(removed_alignments)}/{len(alignments)} alignments due to missing tiltseries: {removed_alignments}"
        )
    alignments = {a.id: a for a in alignments.values() if a and a.tiltseries_id}

    tiltseries = cdp_cache.get_tiltseries([alignment.tiltseries_id for alignment in alignments.values()])
    per_section_parameters = cdp_cache.get_per_section_parameters_by_tiltseries_id([t.id for t in tiltseries.values()])
    # filter out tiltseries that do not have valid CTF parameters
    removed_tiltseries = [t.id for t in tiltseries.values() if not per_section_parameters.get(t.id)]
    if removed_tiltseries:
        logger.error(
            f"Removed {len(removed_tiltseries)}/{len(tiltseries)} tiltseries due to missing CTF parameters: {removed_tiltseries}"
        )
    tiltseries = {t.id: t for t in tiltseries.values() if per_section_parameters.get(t.id)}

    # filter out the alignments that do not have valid tiltseries
    removed_alignments = [a.id for a in alignments.values() if a.tiltseries_id not in tiltseries]
    if removed_alignments:
        logger.error(
            f"Removed {len(removed_alignments)}/{len(alignments)} alignments due to missing tiltseries' CTF parameters: {removed_alignments}"
        )
    alignments = {a.id: a for a in alignments.values() if a and a.tiltseries_id in tiltseries}

    # filter out files that do not have a valid alignment / tiltseries / CTF parameters
    removed_annotation_files = [file.id for file in annotation_files if file.alignment_id not in alignments]
    if removed_annotation_files:
        logger.error(
            f"Removed {len(removed_annotation_files)}/{len(annotation_files)} annotation files due to missing alignments / tiltseries / CTF parameters: {removed_annotation_files}"
        )
    annotation_files = [file for file in annotation_files if file.alignment_id in alignments]
    if not annotation_files:
        raise ValueError(
            "No valid annotation files found. Ensure the annotations contain valid Point or OrientedPoint shapes, and their datasets have tiltseries and alignment information."
        )

    logger.debug(
        f"Processing {len(annotation_files)} annotation files with {len(alignments)} alignments and {len(tiltseries)} tiltseries ..."
    )

    all_optics_dfs = [
        get_optics_df_from_file(
            file, alignments[file.alignment_id], tiltseries[alignments[file.alignment_id].tiltseries_id]
        )
        for file in annotation_files
    ]

    if not no_particles:
        # thread pool because we're downloading data
        with ThreadPoolExecutor(max_workers=THREAD_POOL_WORKER_COUNT) as thread_pool:
            futures = [
                thread_pool.submit(
                    get_particles_df_from_file,
                    file,
                    alignments[file.alignment_id],
                    tiltseries[alignments[file.alignment_id].tiltseries_id],
                )
                for file in annotation_files
            ]

            for fut in tqdm(as_completed(futures), total=len(futures), desc="Downloading particle data"):
                particles_df = fut.result()
                if particles_df.empty:
                    continue
                all_particles_dfs.append(particles_df)

    # filter out empty dataframes
    all_optics_dfs = [df for df in all_optics_dfs if not df.empty]

    if not no_particles:
        all_particles_dfs = [df for df in all_particles_dfs if not df.empty]
        assert len(all_optics_dfs) == len(
            all_particles_dfs
        ), f"Mismatch between number of optics and particles dataframes, likely due to a bug in the code. Annotation file ids: {[a.id for a in annotation_files]}"

    if not all_optics_dfs or (not no_particles and not all_particles_dfs):
        raise ValueError(
            "No valid optics / particle data found. Ensure the annotations contain valid Point or OrientedPoint shapes, and their datasets have tiltseries and alignment information."
        )

    # combine all optics and particles dataframes, remove duplicates, sort by optics group name, and assign optics group numbers
    combined_optics_df = pd.concat(all_optics_dfs, ignore_index=True).drop_duplicates()
    if not no_particles:
        combined_particles_df = pd.concat(all_particles_dfs, ignore_index=True).drop_duplicates()
    for df in [combined_optics_df, combined_particles_df] if not no_particles else [combined_optics_df]:
        # convert "run_XXXXX_tiltseries_YYYYY" format to integers for sorting (see get_optics_group_name)
        df["rlnOpticsGroupNameInt"] = df["rlnOpticsGroupName"].apply(
            lambda x: (int(x.split("_")[1]), int(x.split("_")[3]))
        )
        df.sort_values(by="rlnOpticsGroupNameInt", inplace=True)
        df.drop(columns=["rlnOpticsGroupNameInt"], inplace=True)
    combined_optics_df["rlnOpticsGroup"] = np.arange(1, len(combined_optics_df) + 1)
    if not no_particles:
        combined_particles_df["rlnOpticsGroup"] = combined_particles_df["rlnOpticsGroupName"].map(
            combined_optics_df.set_index("rlnOpticsGroupName")["rlnOpticsGroup"]
        )

    if no_particles:
        return combined_optics_df, None
    else:
        return combined_optics_df, combined_particles_df


def get_tomograms_df(optics_df: pd.DataFrame) -> tuple[pd.DataFrame, list[tuple[int, int]]]:
    """
    Returns a dataframe for the tomograms.star file from the optics dataframe.
    Args:
        optics_df (pd.DataFrame): The optics dataframe containing the optics group information.
    Returns:
        tuple: A tuple containing the tomograms dataframe and a list of alignment and voxel spacing IDs.
    """
    tomograms_df = optics_df.drop_duplicates()
    tomograms_df["rlnMicrographOriginalPixelSize"] = tomograms_df["rlnTomoTiltSeriesPixelSize"]
    tomograms_df["rlnTomoHand"] = TOMO_HAND_DEFAULT_VALUE
    tomograms_df["rlnTomoTiltSeriesStarFile"] = tomograms_df["rlnTomoName"].apply(lambda x: f"tiltseries/{x}.star")

    # add tomogram dimensions rlnTomoSizeX, rlnTomoSizeY, rlnTomoSizeZ
    # reliant on the fact that rlnTomoName is in the format of "run_WWWW_tiltseries_XXXX_alignment_YYYY_spacing_ZZZZ" (see get_tomo_name)
    tomograms_df["alignment_id"] = tomograms_df["rlnTomoName"].apply(lambda x: int(x.split("_")[-3]))
    tomograms_df["voxel_spacing_id"] = tomograms_df["rlnTomoName"].apply(lambda x: int(x.split("_")[-1]))
    alignment_ids = tomograms_df["alignment_id"].unique().tolist()
    voxel_spacing_ids = tomograms_df["voxel_spacing_id"].unique().tolist()
    tomograms_mapping = cdp_cache.get_tomograms_by_alignment_id_and_voxel_spacing_id(
        zip(alignment_ids, voxel_spacing_ids)
    )
    tomograms_dimensions = pd.DataFrame(
        columns=["alignment_id", "voxel_spacing_id", "rlnTomoSizeX", "rlnTomoSizeY", "rlnTomoSizeZ"],
        data=[
            (
                tomogram.alignment_id,
                tomogram.tomogram_voxel_spacing_id,
                tomogram.size_x,
                tomogram.size_y,
                tomogram.size_z,
            )
            for tomograms in tomograms_mapping.values()
            for tomogram in tomograms
        ],
    )
    tomograms_dimensions.drop_duplicates(inplace=True)
    if len(tomograms_dimensions) != len(tomograms_dimensions[["alignment_id", "voxel_spacing_id"]].drop_duplicates()):
        raise ValueError(
            "Multiple tomogram dimensions found for the same alignment ID and voxel spacing ID. This is not supported."
        )

    tomograms_df = tomograms_df.merge(tomograms_dimensions, on=["alignment_id", "voxel_spacing_id"], how="left")
    tomograms_df.drop(columns=["alignment_id", "voxel_spacing_id"], inplace=True)
    return tomograms_df, list(zip(alignment_ids, voxel_spacing_ids))


def generate_individual_tomogram_starfile(
    alignment: cdp.Alignment, voxel_spacing: cdp.TomogramVoxelSpacing, output_dir: Path
) -> tuple[pd.DataFrame, str]:
    """
    Generates an individual tomogram star file for the given alignment and voxel spacing.
    Args:
        alignment (Alignment): The alignment object containing the tiltseries and per-section parameters.
        voxel_spacing (TomogramVoxelSpacing): The voxel spacing object for the tomogram.
        output_dir (Path): The directory where the individual tomogram star file will be saved.
    Returns:
        tuple: A tuple containing the individual tomogram dataframe and the tomogram name.
    """
    tiltseries = list(cdp_cache.get_tiltseries(alignment.tiltseries_id).values())[0]
    per_section_parameters = list(cdp_cache.get_per_section_parameters_by_tiltseries_id(tiltseries.id).values())[0]
    per_section_alignment_parameters = list(
        cdp_cache.get_per_section_alignments_by_alignment_id(alignment.id).values()
    )[0]
    if len(per_section_parameters) < len(per_section_alignment_parameters):
        raise ValueError(
            f"[Run {alignment.run_id}, TiltSeries {tiltseries.id}, Alignment {alignment.id}] Should not have more alignment parameters ({len(per_section_alignment_parameters)}) than CTF parameters ({len(per_section_parameters)})."
        )
    frames = list(cdp_cache.get_frames_by_run_id(alignment.run_id).values())[0]

    per_section_parameters_df = pd.DataFrame(columns=INDIVIDUAL_TOMOGRAM_CTF_COLUMNS)
    for param in per_section_parameters:
        frame = next((f for f in frames if f.id == param.frame_id), None)
        per_section_parameters_df.loc[len(per_section_parameters_df)] = {
            "z_index": param.z_index + 1,  # match RELION's 1-based indexing
            "rlnDefocusU": param.major_defocus,
            "rlnDefocusV": param.minor_defocus,
            "rlnDefocusAngle": param.astigmatic_angle,
            "rlnPhaseShift": param.phase_shift,
            "rlnCtfMaxResolution": param.max_resolution,
            "rlnMicrographPreExposure": frame.accumulated_dose,
        }

    per_section_alignment_parameters_df = pd.DataFrame(
        columns=INDIVIDUAL_TOMOGRAM_ALN_COLUMNS,
        data=[
            {
                "z_index": param.z_index + 1,  # match RELION's 1-based indexing
                "rlnTomoXTilt": param.volume_x_rotation,  # param.x_rotation offset (AreTomo3 beta) is not applied, as per AreTomo3 convention
                "rlnTomoYTilt": param.tilt_angle,  # already accounts for any tilt offset (AreTomo3 alpha)
                "rlnTomoZRot": in_plane_rotation_to_tilt_axis_rotation(np.array(param.in_plane_rotation)),
                "rlnTomoXShiftAngst": param.x_offset,
                "rlnTomoYShiftAngst": param.y_offset,
            }
            for param in per_section_alignment_parameters
        ],
    )

    individual_tomogram_df = pd.merge(
        per_section_parameters_df, per_section_alignment_parameters_df, on="z_index", how="inner"
    )
    unmatched_alignments = per_section_alignment_parameters_df[
        ~per_section_alignment_parameters_df["z_index"].isin(per_section_parameters_df["z_index"])
    ]
    if not unmatched_alignments.empty:
        raise ValueError(
            f"[Run {alignment.run_id}, TiltSeries {tiltseries.id}, Alignment {alignment.id}] Found {len(unmatched_alignments)} alignment parameters that do not match CTF parameters."
        )
    if len(individual_tomogram_df) != len(per_section_alignment_parameters_df):
        raise ValueError(
            f"[Run {alignment.run_id}, TiltSeries {tiltseries.id}, Alignment {alignment.id}] Mismatch between CTF and alignment parameters after merge {len(individual_tomogram_df)} merged != {len(per_section_parameters_df)} CTF != {len(per_section_alignment_parameters_df)} alignment parameters."
        )

    # reorder rows and columns to match RELION format
    individual_tomogram_df.sort_values(by="z_index", inplace=True)
    individual_tomogram_df["rlnMicrographName"] = individual_tomogram_df["z_index"].apply(
        lambda x: f"{str(int(x))}@{TILTSERIES_MRCS_PLACEHOLDER}"
    )
    individual_tomogram_df[TILTSERIES_URI_RELION_COLUMN] = tiltseries.s3_omezarr_dir
    individual_tomogram_df = individual_tomogram_df.drop(columns=["z_index"])
    individual_tomogram_df = individual_tomogram_df[INDIVIDUAL_TOMOGRAM_COLUMNS]

    # generate empty placeholder tiltseries mrc (relative path)
    with mrcfile.new(output_dir / TILTSERIES_MRCS_PLACEHOLDER, overwrite=True) as mrc:
        mrc.set_data(np.zeros((tiltseries.size_z, tiltseries.size_y, tiltseries.size_x), dtype=np.float32))
        mrc.voxel_size = (tiltseries.pixel_spacing, tiltseries.pixel_spacing, 1.0)

    if individual_tomogram_df.isna().any().any():
        raise ValueError(
            f"[Run {alignment.run_id}, TiltSeries {tiltseries.id}, Alignment {alignment.id}] Data contains NA values. This can cause issues with RELION subtomogram extraction. Please check the star file."
        )

    tomo_name = get_tomo_name(alignment.run_id, tiltseries.id, alignment.id, voxel_spacing.id)
    output_path = output_dir / "tiltseries" / f"{tomo_name}.star"
    starfile.write({tomo_name: individual_tomogram_df}, output_path, overwrite=True)
    logger.debug(
        f"[Run {alignment.run_id}, TiltSeries {tiltseries.id}, Alignment {alignment.id}] Wrote individual tomogram star file to {output_path} ({voxel_spacing.voxel_spacing} Å)"
    )

    return individual_tomogram_df, tomo_name


def generate_individual_tomogram_starfiles(
    alignment_and_voxel_spacing_ids: list[tuple[int, int]], output_dir: Path
) -> list[pd.DataFrame]:
    """
    Generates individual tomogram star files for each tuple of alignment ID and voxel spacing ID.
    Args:
        alignment_and_voxel_spacing_ids (list[tuple[int, int]]): List of tuples containing alignment IDs and their corresponding voxel spacing IDs that specify the tomograms to generate.
        output_dir (Path): Directory where the individual tomogram star files will be saved.
    Returns:
        list[pd.DataFrame]: List of DataFrames containing the individual tomogram data.
    """
    logger.info(f"Generating individual tomogram star files in {output_dir} ...")
    all_alignments = cdp_cache.get_alignments([av[0] for av in alignment_and_voxel_spacing_ids]).values()
    all_voxel_spacings = cdp_cache.get_voxel_spacings([av[1] for av in alignment_and_voxel_spacing_ids]).values()

    if any(alignment is None for alignment in all_alignments) or any(
        voxel_spacing is None for voxel_spacing in all_voxel_spacings
    ):
        raise ValueError(
            "Some alignments or voxel spacings are missing. Ensure the alignment and voxel spacing IDs are valid."
        )

    individual_tomograms_dfs = []
    tomo_names = []

    with ThreadPoolExecutor(max_workers=THREAD_POOL_WORKER_COUNT) as thread_pool:
        futures = [
            thread_pool.submit(generate_individual_tomogram_starfile, alignment, voxel_spacing, output_dir)
            for alignment, voxel_spacing in zip(all_alignments, all_voxel_spacings)
        ]

        for fut in tqdm(as_completed(futures), total=len(futures), desc="Generating individual tomogram star files"):
            individual_tomogram_df, tomo_name = fut.result()
            if individual_tomogram_df is not None:
                individual_tomograms_dfs.append(individual_tomogram_df)
                tomo_names.append(tomo_name)

    return individual_tomograms_dfs, tomo_names


def generate_starfiles_from_annotation_files(
    annotation_files: list[cdp.AnnotationFile], output_dir: Path, no_particles_starfile: bool = False
) -> tuple[Path, Path, Path]:
    """
    Generates optics.star / particles.star, tomograms.star, and individual tomogram star files from the given annotation files.
    Args:
        annotation_files (list[cdp.AnnotationFile]): List of annotation files to generate star files from.
        output_dir (Path): Directory where the star files will be saved.
        no_particles_starfile (bool): If True, do not generate particles.star file and instead generate only the optics data in optics.star.
    Returns:
        tuple: A tuple containing the paths to the generated optics.star / particles.star, tomograms.star, and the tiltseries folder.
    """
    start_time = time.time()
    optics_df, particles_df = get_particles_df_optics_df(annotation_files, no_particles=no_particles_starfile)
    tomograms_df, alignment_and_voxel_spacing_ids = get_tomograms_df(optics_df)
    _, tomo_names = generate_individual_tomogram_starfiles(alignment_and_voxel_spacing_ids, output_dir)
    # filter out invalid tomograms from optics, particles, and tomograms dataframes
    tomograms_df = tomograms_df[tomograms_df["rlnTomoName"].isin(tomo_names)]
    tomograms_df_optics_groups = tomograms_df["rlnOpticsGroupName"].unique()
    if not no_particles_starfile:
        particles_df = particles_df[particles_df["rlnTomoName"].isin(tomo_names)]
        particles_df_optics_groups = particles_df["rlnOpticsGroupName"].unique()
        if set(particles_df_optics_groups) != set(tomograms_df_optics_groups):
            raise ValueError(
                f"Optics groups in particles ({particles_df_optics_groups}) and tomograms ({tomograms_df_optics_groups}) do not match. This may cause issues with RELION subtomogram extraction."
            )
        optics_df = optics_df[optics_df["rlnOpticsGroupName"].isin(particles_df_optics_groups)]

    # write files
    particles_path = output_dir / "particles.star"
    tomograms_path = output_dir / "tomograms.star"
    tiltseries_folder_path = output_dir / "tiltseries"
    if no_particles_starfile:
        starfile.write({"optics": optics_df}, particles_path, overwrite=True)
        logger.info(
            f"Wrote {len(optics_df)} optics group(s) to {particles_path}. No particle data was written because no_particles_starfile is True (user-specified flag)."
        )
    else:
        starfile.write({"optics": optics_df, "particles": particles_df}, particles_path, overwrite=True)
        logger.info(f"Wrote {len(optics_df)} optics group(s) and {len(particles_df)} particle(s) to {particles_path}")
    starfile.write({"global": tomograms_df}, tomograms_path, overwrite=True)
    logger.info(f"Wrote {len(tomograms_df)} tomogram(s) to {tomograms_path}")

    end_time = time.time()
    logger.info(f"Finished generating star files in {end_time - start_time:.2f} seconds.")

    logger.debug(cdp_cache.tomograms_cache)
    logger.debug(cdp_cache.alignment_to_tomograms_cache)

    return particles_path, tomograms_path, tiltseries_folder_path


def resolve_annotation_files(
    deposition_ids: list[int] = None,
    deposition_titles: list[str] = None,
    dataset_ids: list[int] = None,
    dataset_titles: list[str] = None,
    organism_names: list[str] = None,
    cell_names: list[str] = None,
    run_ids: list[int] = None,
    run_names: list[str] = None,
    tiltseries_ids: list[int] = None,
    alignment_ids: list[int] = None,
    tomogram_ids: list[int] = None,
    annotation_ids: list[int] = None,
    annotation_names: list[str] = None,
    inexact_match: bool = False,
    ground_truth: bool = False,
) -> list[cdp.AnnotationFile]:
    client = cdp.Client()

    # First filter with information related to the Annotation class; ids are always exact match
    annotation_query_filters = []
    annotation_query_filters.append(get_filter(deposition_ids, cdp.Annotation.deposition.id, False, "deposition IDs"))
    annotation_query_filters.append(
        get_filter(deposition_titles, cdp.Annotation.deposition.title, inexact_match, "deposition titles")
    )
    annotation_query_filters.append(get_filter(dataset_ids, cdp.Annotation.run.dataset.id, False, "dataset IDs"))
    annotation_query_filters.append(
        get_filter(dataset_titles, cdp.Annotation.run.dataset.title, inexact_match, "dataset titles")
    )
    annotation_query_filters.append(
        get_filter(organism_names, cdp.Annotation.run.dataset.organism_name, inexact_match, "organism names")
    )
    annotation_query_filters.append(
        get_filter(cell_names, cdp.Annotation.run.dataset.cell_name, inexact_match, "cell names")
    )
    annotation_query_filters.append(get_filter(run_ids, cdp.Annotation.run.id, False, "run IDs"))
    annotation_query_filters.append(get_filter(run_names, cdp.Annotation.run.name, inexact_match, "run names"))
    annotation_query_filters.append(get_filter(annotation_ids, cdp.Annotation.id, False, "annotation IDs"))
    annotation_query_filters.append(
        get_filter(annotation_names, cdp.Annotation.object_name, inexact_match, "annotation names")
    )
    if ground_truth:
        logger.info("Filtering for ONLY ground truth annotations.")
        annotation_query_filters.append(cdp.Annotation.ground_truth_status == True)  # noqa: E712
    annotation_query_filters = [f for f in annotation_query_filters if f is not None]

    # Then filter with information related to the AnnotationFile class
    tiltseries_query_filters = []
    tiltseries_query_filters.append(get_filter(tiltseries_ids, cdp.TiltSeries.id, False, "tiltseries IDs"))
    tiltseries_query_filters = [f for f in tiltseries_query_filters if f is not None]
    if tiltseries_query_filters:
        tiltseries_list: list[cdp.TiltSeries] = cdp.TiltSeries.find(client, tiltseries_query_filters)
        cdp_cache.tiltseries_cache = {**cdp_cache.tiltseries_cache, **{ts.id: ts for ts in tiltseries_list}}
        alignment_ids_to_aln = {al.id: al for ts in tiltseries_list for al in ts.alignments}
        cdp_cache.alignment_cache = {**cdp_cache.alignment_cache, **alignment_ids_to_aln}
        temp_alignment_ids = list(alignment_ids_to_aln.keys())
        if not temp_alignment_ids:
            raise ValueError("No tiltseries / corresponding alignments found. Please check your filters.")
        alignment_ids = temp_alignment_ids if not alignment_ids else list(set(alignment_ids) & set(temp_alignment_ids))
        if not alignment_ids:
            raise ValueError("No alignment IDs found after filtering. Please check your filters.")

    voxel_spacing_ids = []
    tomogram_query_filters = []
    tomogram_query_filters.append(get_filter(tomogram_ids, cdp.Tomogram.id, False, "tomogram IDs"))
    tomogram_query_filters = [f for f in tomogram_query_filters if f is not None]
    if tomogram_query_filters:
        tomogram_list: list[cdp.Tomogram] = cdp.Tomogram.find(client, tomogram_query_filters)
        cdp_cache.tomograms_cache = {**cdp_cache.tomograms_cache, **{t.id: t for t in tomogram_list}}
        temp_alignment_ids = {t.alignment_id for t in tomogram_list}
        voxel_spacing_ids = [t.tomogram_voxel_spacing_id for t in tomogram_list]
        if not temp_alignment_ids:
            raise ValueError("No tomograms / corresponding alignments found. Please check your filters.")
        alignment_ids = temp_alignment_ids if not alignment_ids else list(set(alignment_ids) & set(temp_alignment_ids))
        if not alignment_ids:
            raise ValueError("No alignment IDs found after filtering. Please check your filters.")

    annotation_file_query_filters = []
    annotation_file_query_filters.append(
        get_filter(alignment_ids, cdp.AnnotationFile.alignment_id, False, "alignment IDs")
    )
    annotation_file_query_filters.append(
        get_filter(voxel_spacing_ids, cdp.AnnotationFile.tomogram_voxel_spacing_id, False, "tomogram voxel spacing IDs")
    )
    annotation_file_query_filters.append(
        get_filter(
            ["Point", "OrientedPoint"], cdp.AnnotationFile.annotation_shape.shape_type, False, "annotation shape types"
        )
    )
    # incorporate the Annotation related filters into the AnnotationFile query filters
    resolved_annotation_ids = []
    if annotation_query_filters:
        annotations: list[cdp.Annotation] = cdp.Annotation.find(client, annotation_query_filters)
        if not annotations:
            raise ValueError("No annotations found matching the provided filters.")
        resolved_annotation_ids = [a.id for a in annotations]
    annotation_file_query_filters.append(
        get_filter(resolved_annotation_ids, cdp.AnnotationFile.annotation_shape.annotation_id, False, "annotation IDs")
    )
    annotation_file_query_filters = [f for f in annotation_file_query_filters if f is not None]

    annotation_files: list[cdp.AnnotationFile] = cdp.AnnotationFile.find(client, annotation_file_query_filters)
    if not annotation_files:
        raise ValueError("No Point / Oriented Point annotation files found matching the provided filters.")

    logger.info(f"Found {len(annotation_files)} annotation files matching the provided filters.")
    return annotation_files


def generate_starfiles(
    output_dir: str | Path,
    deposition_ids: list[int] = None,
    deposition_titles: list[str] = None,
    dataset_ids: list[int] = None,
    dataset_titles: list[str] = None,
    organism_names: list[str] = None,
    cell_names: list[str] = None,
    run_ids: list[str] = None,
    run_names: list[str] = None,
    tiltseries_ids: list[int] = None,
    alignment_ids: list[int] = None,
    tomogram_ids: list[int] = None,
    annotation_ids: list[int] = None,
    annotation_names: list[str] = None,
    inexact_match: bool = False,
    ground_truth: bool = False,
    no_particles_starfile: bool = False,
) -> tuple[Path, Path]:
    """
    Generates star files for annotations based on the specified filters. First resolves all annotation IDs based on the provided filters, then generates the star files given the resolved annotation IDs.
    Returns:
        tuple: A tuple containing the paths to the generated particles.star, tomograms.star, and the tiltseries folder.
    """
    output_dir = Path(output_dir)

    (output_dir / "tiltseries").mkdir(parents=True, exist_ok=True)

    annotation_files = resolve_annotation_files(
        deposition_ids=deposition_ids,
        deposition_titles=deposition_titles,
        dataset_ids=dataset_ids,
        dataset_titles=dataset_titles,
        organism_names=organism_names,
        cell_names=cell_names,
        run_ids=run_ids,
        run_names=run_names,
        tiltseries_ids=tiltseries_ids,
        alignment_ids=alignment_ids,
        tomogram_ids=tomogram_ids,
        annotation_ids=annotation_ids,
        annotation_names=annotation_names,
        inexact_match=inexact_match,
        ground_truth=ground_truth,
    )

    return generate_starfiles_from_annotation_files(annotation_files, output_dir, no_particles_starfile)


@click.command(help="Generate star files needed for subtomogram extraction from a CryoET Data Portal run.")
@cli_options.data_portal_options()
@click.option(
    "--output-dir",
    type=click.Path(file_okay=False, dir_okay=True, writable=True, resolve_path=True),
    required=True,
    help="Directory where star files will be saved.",
)
@click.option("--debug", is_flag=True, help="Enable debug logging.")
def cli(**kwargs):
    debug = kwargs.pop("debug", False)
    setup_logging(debug)
    del kwargs["dry_run"]  # from main cli, not used here
    kwargs = cli_options.flatten_data_portal_args(kwargs)
    generate_starfiles(**kwargs)


if __name__ == "__main__":
    cli()

# Example usage:
# python -m generate.cdp_generate_starfiles --run-ids 16463 --annotation-names "cytosolic ribosome" --output-dir tests/output/data_portal_16363_ribosome
